### ISSUE TITLE
Loading spinner - feature request

### ISSUE THREAD

**Issue by jackkemmish** [Level51/silverstripe-ajax-select-field#7]
Hi there,

I just started using this module and it's super helpful as we have a large `SiteTree` which was crashing a block when loading in the CMS :(

One thing that would be nice to add is a loading spinner in the input field or some kind of feedback to show it's doing something!

Thanks,
Jack

**Comment by dkliemsch** [comment]
Hi Jack, glad that the module has helped you and indeed, a loading indicator sounds like a useful enhancement - therefore I've just released a new version 0.5.1 adding one

**Comment by jackkemmish** [comment]
Hey @dkliemsch,

Yeah it's been a great help thanks!

Amazing, i'll update the package thank you.

Thanks,
Jack
