### ISSUE TITLE
Database value is cleared if publishing block before data loaded

### ISSUE THREAD

**Issue by jackkemmish** [Level51/silverstripe-ajax-select-field#8]
Hi there,

If I publish a block when using this field before the data has fully loaded, it clears the value in the DB.

Is there a way around this?

Thanks,
Jack

**Comment by dkliemsch** [comment]
Hi Jack, 

that was indeed a problem, but I think I've just fixed it with version 0.5.1 - hope that helps!

**Comment by jackkemmish** [comment]
Hey @dkliemsch,

Amazing, i'll check it out! Thank you 👍 

Thanks,
Jack
